//import { test, expect } from '../fixtures/auth.fixture';
import { test, expect } from '@playwright/test';
import { LoginPage } from '../pages/LoginPage';
import { InventoryPage } from '../pages/InventoryPage';
import { CartPage } from '../pages/CartPage';
import { CheckoutPage } from  '../pages/CheckoutPage';

test('e2e shoping', async ({ page }) => {
  //await page.goto('https://www.saucedemo.com/');
  //await page.locator('[data-test="username"]').click();
  //await page.locator('[data-test="username"]').fill('standard_user');
  //await page.locator('[data-test="password"]').click();
  //await page.locator('[data-test="password"]').fill('secret_sauce');
  //await page.locator('[data-test="login-button"]').click();
  await page.locator('[data-test="add-to-cart-sauce-labs-backpack"]').click();
  await page.locator('[data-test="add-to-cart-sauce-labs-bike-light"]').click();
  await page.locator('[data-test="add-to-cart-sauce-labs-bolt-t-shirt"]').click();
  await page.locator('[data-test="add-to-cart-sauce-labs-fleece-jacket"]').click();
  await page.locator('[data-test="shopping-cart-link"]').click();
  await page.locator('[data-test="remove-sauce-labs-backpack"]').click();
  await page.getByText('1Sauce Labs Bike LightA red').click();
  await page.locator('[data-test="remove-sauce-labs-bike-light"]').click();
  await page.locator('[data-test="remove-sauce-labs-bolt-t-shirt"]').click();
  await page.locator('[data-test="remove-sauce-labs-fleece-jacket"]').click();
  await page.locator('[data-test="checkout"]').click();
  await page.locator('.checkout_info').click();
  await page.locator('[data-test="firstName"]').fill('123');
  await page.locator('[data-test="lastName"]').fill('456');
  await page.locator('[data-test="postalCode"]').fill('789');
  await page.locator('[data-test="continue"]').click();
  await expect(page.locator('[data-test="payment-info-label"]')).toContainText('Payment Information:');
  await expect(page.locator('[data-test="payment-info-value"]')).toContainText('SauceCard #31337');
  await expect(page.locator('[data-test="shipping-info-label"]')).toContainText('Shipping Information:');
  await expect(page.locator('[data-test="total-info-label"]')).toContainText('Price Total');
  await expect(page.locator('[data-test="tax-label"]')).toContainText('Tax: $0.00');
});